### ISSUE TITLE
Whats coming in v0.2

### ISSUE THREAD

**Issue by aflacc** [aflacc/ProjectFNF#10]
V0.2 is coming around the corner shortly, and I'm working on some new very helpful features for your mods that people have been wanting to do for a while.

### New Functions
`switchTex(sprite, newTex)` is one you will probably like. You have to define these new textures in a new file I will be calling `tex.hx`, but what this does is you can swap out sprites for something. One use of this is maybe at a certain point in  a song, switch out the characters appearance with another sprite sheet.
`die` kills the player cuz why not :trollface: 
`sethp(hp)` sets the players hp. This is a % value, so 100 would be full hp, 0 would just kill you, 50 would put you at the starting hp.
`alert(message)` brings the player to a alert screen, which would look teh same as the outdated screen but with custom text. the `\n` value is supported.
`skipSong` Sends the player to the next song, or sends them to the main menu if its the last or freeplay

### New Settings
`saveUnlocks` (Bool) bring back the saving week unlocks!
most of the settings mentioned [here](https://github.com/aflacc/ProjectFNF/wiki/Disabling-and-Enabling-features)
`newHealthIcon` (Bool) this is a new way of using health icons, by using a sprite sheet instead of a grid
`freeplayCutscenes` (Bool) weather you want cutscenes to still play from freeplay mode.

### New Mechanics
New input system (maybe)

**Comment by aflacc** [comment]
Ive been getting into haxe functions and think this is a good way to practice

**Comment by MagnusStrom** [comment]
Dialouge n cutscene functions?

**Comment by aflacc** [comment]
> Dialouge n cutscene functions?

yeah by this i mean stuff like (these are just mockups not likely gonna be how it works in the future)
`pan(x, y, speed, easing type)`
`zoom(zoom, speed, easing type)`
`showdia(text)`

**Comment by aflacc** [comment]
Closing because the first beta test will be released later
