### ISSUE TITLE
[6] Certain note skins crash on Week 6

### ISSUE THREAD

**Issue by VMGuy23** [aflacc/ProjectFNF#100]
ProjectFNF version: Latest commit as of the creation of this issue
Type of issue: Crash
Severity: 6
Description: When using certain note skins (WAFELS3) on week 6, the game crashes..
Repository: [my portrait mode ver, no major code differences](https://github.com/VMGuy23-1/ProjectFNF-Mobile)

**Comment by MagnusStrom** [comment]
Fixed

**Comment by VMGuy23** [comment]
nice
