### ISSUE TITLE
[10] Arrows are all invisible

### ISSUE THREAD

**Issue by clothing-hanger** [aflacc/ProjectFNF#101]
ProjectFNF version 0.3-d:
Type of issue Visual
Severity 10
Description The arrows are literally just invisible. I changed a few setting before playing for the first tine but I have changed every setting back to default and even downloaded the game again

**Comment by MagnusStrom** [comment]
Whats your modifiers list?

**Comment by clothing-hanger** [comment]
Like in the settings?
Dad notes do damage false
Dad notes can kill false
Dad notes visible true
BF notes visible true
Stuns block inputs false

**Comment by MagnusStrom** [comment]
What note skin?
Are you compiling or using binaries?

**Comment by clothing-hanger** [comment]
WAIT it literally just started working, I have no idea what changed but
it's working now

**Comment by clothing-hanger** [comment]
I'm using the etterna note skin, and I didn't compile it I just downloaded
it from the GitHub, it's working now, I don't know what changed but it
started working. I have closed the game a few times so maybe somehow that
fixed it? I really don't know but it's working now. If I knew what I did to
get it to work I would say but I really don't

**Comment by VMGuy23** [comment]
close the issue
