### ISSUE TITLE
where can you toggle the icongrid v2[?]

### ISSUE THREAD

**Issue by Nikz2323** [aflacc/ProjectFNF#102]
Where can you toggle the icons so it shows the icongridv2?

**Comment by VMGuy23** [comment]
it was removed

**Comment by Nikz2323** [comment]
> it was removed

aw man

**Comment by Nikz2323** [comment]
> it was removed

in which build was it tho,to see if i can download it

**Comment by MagnusStrom** [comment]
https://github.com/aflacc/ProjectFNF/releases/tag/v0.3-c
