### ISSUE TITLE
[#] The game don't save the keybinds when exiting the game and coming back

### ISSUE THREAD

**Issue by TonyRonii** [aflacc/ProjectFNF#103]
ProjectFNF version: 0.4
Type of issue: Don't save keybinds when exiting the game and coming back
Severity: Not big just kinda annoying
Description: When i boot the game back up my keybinds i set before don't work unless i put them back
Repository:

**Comment by MagnusStrom** [comment]
Cannot replicate, can anyone else?

**Comment by TonyRonii** [comment]
i dont know the only another person that i know is having the same problem is my friend but maybe its our game

**Comment by l1ttleO** [comment]
> Cannot replicate, can anyone else?

Well I can. They are *saved*, but aren't *applied* (i.e. don't work in-game) unless saved again

**Comment by TonyRonii** [comment]
Yep

**Comment by TonyRonii** [comment]
sorry for not being more specific this is my first time writing an issue on here

**Comment by MagnusStrom** [comment]
All good.
Have you been pressing ENTER? or ESC?

**Comment by TonyRonii** [comment]
> All good.
> Have you been pressing ENTER? or ESC?

Esc

**Comment by TonyRonii** [comment]
Am I supposed to click enter?

**Comment by TonyRonii** [comment]
I click enter to click on the keybinds and esc to exit and save

**Comment by SKBotNL** [comment]
Have the same problem, when setting my keybinds and restarting the game the keybinds reset to the default keybinds but if i go to the settings menu and change my keybinds they are there (my custom keybinds) and when i press esc again it works

**Comment by MagnusStrom** [comment]
Looking into this. This seems to have been an issue for a bit

**Comment by MagnusStrom** [comment]
Could someone let me know if this issue is fixed in the latest commit?

**Comment by l1ttleO** [comment]
> Could someone let me know if this issue is fixed in the latest commit?

ITS FIXED ASDASGAEDFSADGSFTG

**Comment by MagnusStrom** [comment]
Great! Looks like I just wasn't calling the bind function on savedata. Closing
