### ISSUE TITLE
[#] When you change the character in the chart menu and click enter the game crashes

### ISSUE THREAD

**Issue by TonyRonii** [aflacc/ProjectFNF#104]
ProjectFNF version:0.4
Type of issue:Crash
Severity: 7/10 
Description:(Sorry for making another issue im trying to convert me and my friends mod on this enigne)Go to a song and change the character and start the song and boom the game crashes
Repository:

**Comment by MagnusStrom** [comment]
Any debug notification?

**Comment by TonyRonii** [comment]
What is that?

**Comment by MagnusStrom** [comment]
I'm unable to replicate this issue.

**Comment by SKBotNL** [comment]
Maybe this helps (yes i recreated the issue):
```
Called from hxcpp::__hxcpp_main
Called from ApplicationMain::main ApplicationMain.hx line 25
Called from ApplicationMain::create ApplicationMain.hx line 130
Called from lime.app.Application::exec lime/app/Application.hx line 150
Called from lime._internal.backend.native.NativeApplication::exec lime/_internal/backend/native/NativeApplication.hx line 146
Called from lime._internal.backend.native.NativeApplication::handleRenderEvent lime/_internal/backend/native/NativeApplication.hx line 370
Called from lime.app._Event_lime_graphics_RenderContext_Void::dispatch lime/_internal/macros/EventMacro.hx line 91
Called from openfl.display.Stage::__onLimeRender openfl/display/Stage.hx line 1950
Called from openfl.display.Stage::__broadcastEvent openfl/display/Stage.hx line 1166
Called from openfl.display.DisplayObject::__dispatch openfl/display/DisplayObject.hx line 1399
Called from openfl.events.EventDispatcher::__dispatchEvent openfl/events/EventDispatcher.hx line 402
Called from flixel.FlxGame::onEnterFrame flixel/FlxGame.hx line 551
Called from flixel.FlxGame::step flixel/FlxGame.hx line 677
Called from flixel.FlxGame::update flixel/FlxGame.hx line 747
Called from flixel.FlxState::tryUpdate flixel/FlxState.hx line 202
Called from PlayState::update PlayState.hx line 1776
Called from MusicBeatState::update MusicBeatState.hx line 65
Called from flixel.addons.ui.FlxUIState::update flixel/addons/ui/FlxUIState.hx line 212
Called from flixel.group.FlxTypedGroup::update flixel/group/FlxGroup.hx line 175
Called from Character::update Character.hx line 544
Error : Null Object Reference
```

**Comment by MagnusStrom** [comment]
`null object refrence`
trying to access an object that doesnt exist
`Called from Character::update Character.hx line 544`
check like 544

**Comment by MeowzS-WANThelp** [comment]
HI can someone explain me how to code? (bc i want to make a song)

**Comment by SKBotNL** [comment]
> HI can someone explain me how to code? (bc i want to make a mod)
You dont really need to code, see [here](https://github.com/aflacc/ProjectFNF/wiki/Setup-Workspace) for some explanation which might help you. Also, please dont do this in a random issue and just make a new issue (question) or something

**Comment by SKBotNL** [comment]
> `null object refrence`
> trying to access an object that doesnt exist
> `Called from Character::update Character.hx line 544`
> check like 544

Line 544 is: `if (animation.curAnim.name.startsWith('sing'))`

Whole function:
```haxe
	override function update(elapsed:Float)
	{
		if (!curCharacter.startsWith('bf'))
		{
			if (animation.curAnim.name.startsWith('sing'))
			{
				holdTimer += elapsed;
			}

			var dadVar:Float = 4;

			if (curCharacter == 'dad')
				dadVar = 6.1;
			if (holdTimer >= Conductor.stepCrochet * dadVar * 0.001)
			{
				dance();
				holdTimer = 0;
			}
		}

		switch (curCharacter)
		{
			case 'gf':
				if (animation.curAnim.name == 'hairFall' && animation.curAnim.finished)
					playAnim('danceRight');
		}

		super.update(elapsed);
	}

**Comment by MagnusStrom** [comment]
then your bf sprites/one of your cusdtom characters are messed up. this is not a pfnf issue

**Comment by SKBotNL** [comment]
> then your bf sprites/one of your cusdtom characters are messed up. this is not a pfnf issue

I am not using custom characters, I am just changing the character in the charting menu to a character that exists already in the actual game

**Comment by MeowzS-WANThelp** [comment]
this is possible to fix?
![image](https://user-images.githubusercontent.com/88287248/127781526-9d972bf4-ac60-4092-ba2e-014bb364d672.png)

**Comment by SKBotNL** [comment]
> this is possible to fix?
> ![image](https://user-images.githubusercontent.com/88287248/127781526-9d972bf4-ac60-4092-ba2e-014bb364d672.png)

Please dont do that in this issue

**Comment by MeowzS-WANThelp** [comment]
ok
sorry :(

**Comment by MagnusStrom** [comment]
I'm going to close this because I can't replicate it.
