### ISSUE TITLE
Why logo not bumpin[?]

### ISSUE THREAD

**Issue by MeowzS-WANThelp** [aflacc/ProjectFNF#108]
Hi i have 2 issues but i chosed the main that is when i edit logo for fnf it broke like this
![image](https://user-images.githubusercontent.com/88287248/127781339-34a20a4f-8ea1-4d53-8f38-d07367f6985b.png)

**Comment by MeowzS-WANThelp** [comment]
The other is this that my week no showed up in need to scroll
![image](https://user-images.githubusercontent.com/88287248/127781365-882545b5-c6ea-4f6a-bc8a-d674fbbac35b.png)

**Comment by SKBotNL** [comment]
> Hi i have 2 issues but i chosed the main that is when i edit logo for fnf it broke like this
> ![image](https://user-images.githubusercontent.com/88287248/127781339-34a20a4f-8ea1-4d53-8f38-d07367f6985b.png)

The ProjectFNF logo is not bumping aswell, it might be intentional or a bug

**Comment by SKBotNL** [comment]
> The other is this that my week no showed up in need to scroll
> ![image](https://user-images.githubusercontent.com/88287248/127781365-882545b5-c6ea-4f6a-bc8a-d674fbbac35b.png)

I think thats rather an issue with your mod than ProjectFNF

**Comment by SKBotNL** [comment]
It has something to do with this for sure
![image](https://user-images.githubusercontent.com/68018116/127781706-c9f70fef-b01f-49e8-8bc3-eeb00ae9e6ed.png)

**Comment by MagnusStrom** [comment]
Because theres no bump animation. add the animation and try again
