### ISSUE TITLE
BF's Icon going a bit nuts in Week 5.

### ISSUE THREAD

**Issue by SnuwTheFox** [aflacc/ProjectFNF#11]
Woops, seems BF's icon likes to break a bit.

Does his damaged/losing sprite even though the parents are losing.
(Same also happens with Winter Horrorland.)
![image](https://user-images.githubusercontent.com/75770504/114773660-3b7a5f80-9d67-11eb-9263-6a32921cd363.png)

**Comment by SnuwTheFox** [comment]
I should mention this is a Week 5 only issue, it seems. Everywhere else the icon works as intended.
![image](https://user-images.githubusercontent.com/75770504/114773928-8a27f980-9d67-11eb-990c-a974e02f8962.png)

**Comment by aflacc** [comment]
weird. I might have done the order wrong.

**Comment by aflacc** [comment]
yeah this is an issue with the orders

**Comment by aflacc** [comment]
This is fixed in v0.2 but I can move it to v0.1-e which could be a final unplanned release. I really don't know. Its not hard to fix thru the code.

**Comment by aflacc** [comment]
Closing this issue since I'm pretty sure its fixed. If not you can fix it in healthicon.hx by simply changing the values
