### ISSUE TITLE
[#] Lime test windows no responding or idk

### ISSUE THREAD

**Issue by MeowzS-WANThelp** [aflacc/ProjectFNF#111]
Why when i put command Lime test windows shows up these
![image](https://user-images.githubusercontent.com/88287248/127856043-80d2dcc0-f9a9-418c-917a-c87466cf9de1.png)

**Comment by MagnusStrom** [comment]
it's because its... making the game.

**Comment by MeowzS-WANThelp** [comment]
oh ok and how much time gonna take if you know

**Comment by MeowzS-WANThelp** [comment]
i have waited 1 hour and nothink happened

**Comment by SKBotNL** [comment]
> i have waited 1 hour and nothink happened

Because it gave an error...

**Comment by MagnusStrom** [comment]
Sorry for that bro LMAO
run `haxelib update` and try again

**Comment by SKBotNL** [comment]
> Sorry for that bro LMAO
> run `haxelib update` and try again

I think this could be a problem with extension-webm

**Comment by SKBotNL** [comment]
like the wrong extension-webm version/repo installed

**Comment by MagnusStrom** [comment]
no its not
read error

**Comment by MeowzS-WANThelp** [comment]
is it now ok?
![image](https://user-images.githubusercontent.com/88287248/127866072-d0f3f333-c07b-4464-8b63-416d0166942f.png)

**Comment by SKBotNL** [comment]
> no its not
> read error

Ive had the issue many times and reinstalling extension-webm fixed it...

**Comment by MeowzS-WANThelp** [comment]
idk what to do bc im new to code 
![image](https://user-images.githubusercontent.com/88287248/127868932-909b85a6-3f4d-4d70-8b69-0ba52c2d7473.png)

**Comment by SKBotNL** [comment]
> idk what to do bc im new to code
> ![image](https://user-images.githubusercontent.com/88287248/127868932-909b85a6-3f4d-4d70-8b69-0ba52c2d7473.png)

Try running `haxelib git extension-webm https://github.com/KadeDev/extension-webm`

**Comment by SKBotNL** [comment]
And after that try to build

**Comment by MeowzS-WANThelp** [comment]
ok

**Comment by MeowzS-WANThelp** [comment]
it says these can help me with chart and code bc idk...
![image](https://user-images.githubusercontent.com/88287248/127869289-f53d854c-6256-45d3-8905-b436b45c57fc.png)

**Comment by MeowzS-WANThelp** [comment]
![image](https://user-images.githubusercontent.com/88287248/127869715-309a08ee-9f11-4fcf-9cc4-ac368be7517e.png)

**Comment by SKBotNL** [comment]
> it says these can help me with chart and code bc idk...
> ![image](https://user-images.githubusercontent.com/88287248/127869289-f53d854c-6256-45d3-8905-b436b45c57fc.png)

Its `haxelib` not `axelib`

**Comment by MeowzS-WANThelp** [comment]
![image](https://user-images.githubusercontent.com/88287248/127870192-df19034b-b3f5-45ef-a687-f49cc4ed1c12.png)

**Comment by SKBotNL** [comment]
Yes. When its done try to build again

**Comment by MeowzS-WANThelp** [comment]
thanks

**Comment by MeowzS-WANThelp** [comment]
![image](https://user-images.githubusercontent.com/88287248/127870516-c68a2097-096f-49cf-88d7-414bfc813417.png)

**Comment by MeowzS-WANThelp** [comment]
![image](https://user-images.githubusercontent.com/88287248/127870607-e54babf5-aea1-4122-a65d-9a3248de2e64.png)

**Comment by SKBotNL** [comment]
Is this a mod or something?

**Comment by MeowzS-WANThelp** [comment]
a new character yes mod

**Comment by MeowzS-WANThelp** [comment]
doyou want to help me ?

**Comment by SKBotNL** [comment]
Then something is probably wrong with your mod

**Comment by MeowzS-WANThelp** [comment]
![image](https://user-images.githubusercontent.com/88287248/127870999-356f6a75-3200-4965-a11a-2aa0721e6044.png)
is there somethink wrong

**Comment by MeowzS-WANThelp** [comment]
![image](https://user-images.githubusercontent.com/88287248/127871140-618f10d0-e5f3-4ee2-bc02-2c03c3d9d085.png)

**Comment by MeowzS-WANThelp** [comment]
![image](https://user-images.githubusercontent.com/88287248/127871182-3c971cf0-97df-4844-b29e-acfe1b54fca2.png)

**Comment by MagnusStrom** [comment]
Bro cmon. your asking for kade engine help in projectFNF.

**Comment by MagnusStrom** [comment]
We aren't here to help you for that.
