### ISSUE TITLE
[2] Health 101%

### ISSUE THREAD

**Issue by SKBotNL** [aflacc/ProjectFNF#113]
ProjectFNF version: 0.4-b (latest commit)
Type of issue: Mechanics 
Severity: 2
Description: Sometimes when playing a song it says that you have 101% health

![image](https://user-images.githubusercontent.com/68018116/129443653-d37094d7-dc8a-4145-bf13-e4d66a240170.png)

**Comment by l1ttleO** [comment]
It's because how it's coded. I assume it's because the health percentage is updated before the check that sets the health back to 100% if it's above 100% runs

**Comment by MagnusStrom** [comment]
^^^ This is the new healthbar code.
