### ISSUE TITLE
where borgir????????????????????????????

### ISSUE THREAD

**Issue by cube-the-borgir** [aflacc/ProjectFNF#115]
where the borger doing???????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
![tenor-removebg-preview](https://user-images.githubusercontent.com/89224016/130143842-3ba2c64c-d201-4f70-b644-69d6cfb7b15a.png)

**Comment by VMGuy23** [comment]
no, he isnt
