### ISSUE TITLE
CONFIGTitle Does not work when set to false

### ISSUE THREAD

**Issue by MagnusStrom** [aflacc/ProjectFNF#14]
Severity of issue: Medium
Link to Repository of Mod (Reccomended): Its basically a clone of this one
Describe the bug and how to recreate it: In Config.hx, setting "CONFIGTitle" to false still uses the projectfnf title.

Extra notes:

**Comment by aflacc** [comment]
ok so uh I'm still working on the config file. Inside titlestate theres a variable called PFNFLogo or somehting turn that off (set it to false)

**Comment by aflacc** [comment]
I'm gonna leave this issue open, and I'll close it when I finish the config file functionality

**Comment by aflacc** [comment]
Fixed
