### ISSUE TITLE
Do you guys want to see YouTube tutorials on how to use ProjectFNF?

### ISSUE THREAD

**Issue by aflacc** [aflacc/ProjectFNF#17]
I had this idea brought to me by a few people in the Discord, and I think I could do this. They would be short. If you support this Idea, simply react to this message with 👍. Also reply with your ideas for tutorials as well because I might make the first one today

**Comment by aflacc** [comment]
Sorry, React to *this* message

**Comment by aflacc** [comment]
You guys should give your feedback on this

**Comment by VMGuy23** [comment]
If Project FNF is a library for creating custom versions of FNF using source from FNF, then yes. Otherwise, yes.

**Comment by AKASme** [comment]
yes

**Comment by GalaxyzDoneDidCoding** [comment]
Yeah That Would be helpful

**Comment by shmabitt** [comment]
yes, it would be really helpful

**Comment by aflacc** [comment]
I'm seeing an overwelmingly positive amount of feedback. I'll run a poll in the discord later on what the first tutorial will be on

**Comment by VMGuy23** [comment]
What about running it here? not everyone has discord, but anyone who says yes here can reply

**Comment by aflacc** [comment]
well yeah we are gonna do

**Comment by VMGuy23** [comment]
probably the first tutorial should be basic usage. Like to agree.
