### ISSUE TITLE
Bug Report: icons still glitchy

### ISSUE THREAD

**Issue by VMGuy23** [aflacc/ProjectFNF#19]
Severity of issue: Low
Link to Repository of Mod (Reccomended): Unmodded
Describe the bug and how to recreate it: As in previous issues, the boyfriend icon still goes dead when the other one does.

Extra notes:
I like your additions to the game

**Comment by aflacc** [comment]
which version are you using

**Comment by VMGuy23** [comment]
The latest itch.io version, it was fixed in self-compiled though

**Comment by aflacc** [comment]
Ah, I haven't put out v0.2 on itch but I'll get started on that rn
