### ISSUE TITLE
Extra version info

### ISSUE THREAD

**Issue by VMGuy23** [aflacc/ProjectFNF#20]
Describe the type of Feature (Quality of Life, Mechanic, etc.): (most likely) Quality of Life
Describe your Suggestion:
Add the FNF version ProjectFNF is built on in the corner of the screen

**Comment by aflacc** [comment]
Actually ever since I added the mod title thing in the config the version thing gets the metadata of the app in `project.xml` to get the version. I might put the actual FNF version in the right or something. I like the idea

**Comment by aflacc** [comment]
Leaving this open until I add this

**Comment by VMGuy23** [comment]
I'll leave it open for you (and also because I want to anyway)

**Comment by aflacc** [comment]
I kinda uhhh replaced the version metadata when I was adding the ProjectFNF version. (whoops)

**Comment by aflacc** [comment]
:trollface:

**Comment by VMGuy23** [comment]
Oh :) maybe when you update the version of FNF used by ProjectFNF you can add the version in there

**Comment by aflacc** [comment]
> Oh :) maybe when you update the version of FNF used by ProjectFNF you can add the version in there

I might figure out a way to display both of them because the metadata can actually only hold one version.

**Comment by aflacc** [comment]
ill get to work on it in a bit

**Comment by VMGuy23** [comment]
Nice

**Comment by aflacc** [comment]
do u remember what version it uses it uses the latest github build

**Comment by aflacc** [comment]
Closign this just cuz I have it planned and on my personal ProjectFNF trello
