### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by VMGuy23** [aflacc/ProjectFNF#21]
Severity of issue: Kinda high
Describe the bug and how to recreate it:
Do `lime test html5 -debug` and play through week 6, after textboxes the game freezes
Extra notes:

**Comment by aflacc** [comment]
I don't think theres a mp3 version of something in week 6. HTML5 uses mp3 instead of ogg. If it tries to play a sound that doesn't exist in the builds format (HTML5 and mp3, Windows and ogg) it will crash.

**Comment by VMGuy23** [comment]
Good to know, maybe see if it's in ninjamuffin99/Funkin and copy it from themre

**Comment by aflacc** [comment]
Check your files for any sounds that have an ogg but not mp3. You can use apps like audacity to convert them and get an mp3 version too

**Comment by VMGuy23** [comment]
Yeah I have audacity, I'll check and might manually copy from ninjamuffin99's one

**Comment by aflacc** [comment]
when does the crash happen is it like on thorns

**Comment by VMGuy23** [comment]
Just after cutscene ends on thorns yep

**Comment by VMGuy23** [comment]
I noticed no OGG's in compiled when they are in source code

**Comment by aflacc** [comment]
its because these three files dont have a mp3 variant:
[intro1-pixelevil](https://github.com/aflacc/ProjectFNF/blob/master/assets/shared/sounds/intro1-pixelevil.ogg) [intro2-pixelevil](https://github.com/aflacc/ProjectFNF/blob/master/assets/shared/sounds/intro2-pixelevil.ogg) [intro3-pixelevil](https://github.com/aflacc/ProjectFNF/blob/master/assets/shared/sounds/intro3-pixelevil.ogg) [introGo-pixelevil](https://github.com/aflacc/ProjectFNF/blob/master/assets/shared/sounds/introGo-pixelevil.ogg)

**Comment by aflacc** [comment]
I would assume that south going to monster will also crash. so [BIGTHUNDER](https://github.com/aflacc/ProjectFNF/blob/master/assets/shared/sounds/BIGTHUNDER.ogg) also will need a mp3

**Comment by aflacc** [comment]
if you create them you could even create a pull rq or send me them on discord and ill put them in the files

**Comment by VMGuy23** [comment]
Does -pielevil even exist as an ogg?

**Comment by aflacc** [comment]
yeah click the links I sent

**Comment by aflacc** [comment]
they are all in`assets/shared/sounds`

**Comment by aflacc** [comment]
also all those sounds are projectfnf sounds and do not exist in the original game

**Comment by VMGuy23** [comment]
About to make pull request just converting them into mp3s

**Comment by aflacc** [comment]
projectfnfs first pr!!! :D

**Comment by VMGuy23** [comment]
Yep, also found errorMenuNeo.ogg to convert

**Comment by aflacc** [comment]
> Yep, also found errorMenuNeo.ogg to convert
that one goes completely unused

**Comment by VMGuy23** [comment]
I know, but could be used later so might as well convert it

**Comment by aflacc** [comment]
okie

**Comment by VMGuy23** [comment]
Created PR, I will now close this
