### ISSUE TITLE
Console opens in Week 4

### ISSUE THREAD

**Issue by VMGuy23** [aflacc/ProjectFNF#24]
Severity of issue: Low
Link to Repository of Mod (Reccomended): https://github.com/aflaxx/ProjectFNF
Describe the bug and how to recreate it:
Run `lime test html5 -debug` and play week 4
Extra notes:
![Web capture_3-5-2021_18295_localhost](https://user-images.githubusercontent.com/81651922/116910406-7f150a80-ac3d-11eb-954d-9445fbd8c349.jpeg)

**Comment by VMGuy23** [comment]
Pretty sure it opens in all weeks actually

**Comment by aflacc** [comment]
thats what `-debug` does

**Comment by VMGuy23** [comment]
It only shows if error, played with -debug before without this

**Comment by aflacc** [comment]
by any chance are you in the discord server

**Comment by VMGuy23** [comment]
No, don't have discord, why?

**Comment by aflacc** [comment]
i was gonna give u a contributer role but its ok

**Comment by aflacc** [comment]
Closing this because this is intentional. If you don't want the debug menu open I think f2 toggles it or you can just not use `-debug`

**Comment by VMGuy23** [comment]
Also probably going to get discord somewhere near the end of the month

**Comment by aflacc** [comment]
coolio
