### ISSUE TITLE
ok so basically

### ISSUE THREAD

**Issue by aflacc** [aflacc/ProjectFNF#31]
:troll:

**Comment by aflacc** [comment]
dude dont make joke issues its unfunny and whoever does it is unfunny forever

**Comment by VMGuy23** [comment]
Forgot to switch accounts?

**Comment by aflacc** [comment]
> Forgot to switch accounts?

what are you talking about

**Comment by VMGuy23** [comment]
You opened the issue:
![image](https://user-images.githubusercontent.com/81651922/117352105-770bd380-aea6-11eb-9cff-aa79fcde6fc2.png)
Then you replied to yourself:
![image](https://user-images.githubusercontent.com/81651922/117352142-8559ef80-aea6-11eb-8db1-f606e5ec41f7.png)

**Comment by aflacc** [comment]
windows is flawless

**Comment by VMGuy23** [comment]
daylight saving time made it go _against_ the BIOS time which I set and be wrong.
