### ISSUE TITLE
What is in your opinion the most important thing to fix, add or remove in projectfnf

### ISSUE THREAD

**Issue by aflacc** [aflacc/ProjectFNF#34]
I'm just curious what I should do

**Comment by aflacc** [comment]
> Fix the input system

god dammit core

**Comment by aflacc** [comment]
i told you to shut up about the inputs im working on it okay

**Comment by aflacc** [comment]
grrrrgrrrgrgrgrgrrr

**Comment by VR-Core** [comment]
Just do it

**Comment by Heyitstoes** [comment]
fix the input system

**Comment by aflacc** [comment]
I AM WORKING ON IT

**Comment by aflacc** [comment]
NO

**Comment by VR-Core** [comment]
Yes

**Comment by aflacc** [comment]
do you want me to get burned out

**Comment by VR-Core** [comment]
This is how it feels when you rush me on stuff Aflac

**Comment by aflacc** [comment]
yes I know i realize that now

**Comment by VR-Core** [comment]
Perfect

**Comment by Heyitstoes** [comment]
remove herobrine

**Comment by VR-Core** [comment]
GASP

**Comment by aflacc** [comment]
gdnjfgndkgrnvajsneovmutbhigobsnihtgdfnhvjkltrne

**Comment by aflacc** [comment]
so anyways pog

**Comment by aflacc** [comment]
also core I finished the youtube video did you see it

**Comment by aflacc** [comment]
all my homies hate discord github issues is my fren now

**Comment by aflacc** [comment]
beep

**Comment by Heyitstoes** [comment]
_**beep**_

**Comment by aflacc** [comment]
**_beep_**

**Comment by aflacc** [comment]
### _**beep**_

**Comment by aflacc** [comment]
we have returned to monke

**Comment by aflacc** [comment]
oaoaooaoaoaoao

**Comment by aflacc** [comment]
oh my god

I'm gonna say this once more and then I'm not repeating myself.
I have an input system in development by a friend and we are going to use it. There is also a good chance we will just be using the Week 7 input system. Please stop asking for the input system. We will get one when we get one.

**Comment by Heyitstoes** [comment]
Well Aflac, you can't really blame them. A broken input system ruins the experience for the mods they create with YOUR engine. You can't get mad at them for a big bug that you haven't fixed.

**Comment by VMGuy23** [comment]
Revamped debug menu AND the cursor disappears after closing the debug menu

**Comment by aflacc** [comment]
hippity hoppity this is now discussion tabs propety
