### ISSUE TITLE
[8] Lua error causes compile fail

### ISSUE THREAD

**Issue by VMGuy23** [aflacc/ProjectFNF#41]
ProjectFNF version: Latest from GitHub
Type of issue: Compile error
Severity: 8
Description: Install linc_luajit from Haxelib (Linux specific, maybe) and try compiling
Repository: 
Here

```
/usr/share/haxe/lib/linc_luajit/0,0,2/llua/Lua.hx:492: characters 43-61 : Abstract<cpp.Callable> has no field fromStaticFunction
/usr/share/haxe/lib/linc_luajit/0,0,2/llua/Lua.hx:526: characters 42-60 : Abstract<cpp.Callable> has no field fromStaticFunction

```
When compiling with Linux, not html5, I get this:
```
Error: In file included from include/llua/Lua_helper.h:11,
                 from ./src/__boot__.cpp:779:
/usr/share/haxe/lib/linc_luajit/0,0,2//linc/linc_lua.h:10:10: fatal error: ../lib/lua/src/lua.hpp: No such file or directory
   10 | #include "../lib/lua/src/lua.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by aflacc** [comment]
Hm.... I honestly don't know. I would assume it has something to do with modcharts since the only time Lua stuff is actually used is in the Modcharts. I think just deleting modchartstate.hx will fix it.

**Comment by VMGuy23** [comment]
Will try

**Comment by VMGuy23** [comment]
Didn't work.

**Comment by VMGuy23** [comment]
Looks like an HTML5-only issue. Linux build works after a fix in luajit.

**Comment by aflacc** [comment]
Yeah LUA doesn't like HTML5

**Comment by VMGuy23** [comment]
What else apart from modcharts.hx did you add?

**Comment by aflacc** [comment]
closing this because I might be completely changing the modcharts

**Comment by VMGuy23** [comment]
Nice.
