### ISSUE TITLE
about the new licensing thing

### ISSUE THREAD

**Issue by aflacc** [aflacc/ProjectFNF#45]
https://github.com/ninjamuffin99/Funkin/issues/1106#issuecomment-841754730 lmao im not explaining everything he did it for me :trollface:

**Comment by aflacc** [comment]
any mods online pin the discord rpc message pls

**Comment by aflacc** [comment]
webhook*

**Comment by namazso** [comment]
I think you should just don't pull any commits from upstream until they figure this out (which will hopefully happen by week 7)
