### ISSUE TITLE
Dialogue in ProjectFNF will be completely revamped.

### ISSUE THREAD

**Issue by aflacc** [aflacc/ProjectFNF#47]
So I'm going to re-write how dialogue is going to work for projectfnf in a bit and I'm gonna just explain now how its going to work.

## Portraits
So there are two different ways I might go about doing this. One of them saves space and time, the other one would be much easier to code in. The first method would be to use Spritesheets for each one. Now, I will be including a template in the files if I do this, and it will have a pre-coded xml that would have predefined expressions. inside dialogue, to change the expression, you would do the following: `:bf:neutral:`. Notice how there's two sections of the dialogue. the second one would be the expression.
The second method will be a million times better to add expressions in. There will be a "portraits" folder in shared, and it will contain files for each one. To call on one, you simply type the name of the file. For example, if I had a dad angry dialogue sprite, I would use `:dadAngry:` if I named the file `dadAngry.png`. Basically it will look for a file with the respected name in the portraits folder.

## Animations
Because this new format won't have animations, I will be hardcoding in animations for the dialouge. It won't really have an animation, but I can try my best

I'm not really 100% sure I want to do the other ideas so I will hold on explaining them here.

**Comment by aflacc** [comment]
also rq i'm also gonna be putting the story mode color changes thing in the config so u dont have to actually use it.

**Comment by kijikodev** [comment]
cool

**Comment by aflacc** [comment]
Okay so  this is gonna come out as a Beta Test.

**Comment by aflacc** [comment]
Closing this issue cuz the fact that I'm seeing issues when its just announcement posts annoys me. I need a proper way to create these
