### ISSUE TITLE
Where I'm trying to go with ProjectFNF

### ISSUE THREAD

**Issue by aflacc** [aflacc/ProjectFNF#52]
Okay so, some of you guys might be curious about what I plan on doing to make ProjectFNF unique (other than the already existing stuff). and I want to go ahead and explain what I at least hope on adding to ProjectFNF, listed in order from Most Likely to be added to Least likely:

### Screenshots
Ok so I don't think this would be too hard to do but I would add a keybind that when pressed would capture your screen

### "Mod-ules"
A Mod-ule is basically a really easy way to add mods to your build of ProjectFNF. Basically, there would be a "Modules" folder in the folder with the .exe and assets and stuff that you could drag a "Module" folder into which would contain assets and some code. You would be able to insert mods into your build and they would be able to be all played in one .exe. I don't know how I would go about creating the Module folder but this is something I had in mind.

### Kade Engine Compatibility
I know what you're thinking: "aflac don't u hate kade engine?" and your right i do but thats just cuz its slow for me. Its not a bad engine itself. Most of the hate is just a joke since I do have my own engine and would say its better cuz I made it. I don't know how I'd go about this at all I just kinda was one day vibin and was like "that would be a cool idea"

**Comment by aflacc** [comment]
fuck i didnt mean to send this yet. oh well

**Comment by VMGuy23** [comment]
Well...
KE doesn't have coloured healthbars, does it?

**Comment by aflacc** [comment]
> Well...
> KE doesn't have coloured healthbars, does it?

true

**Comment by VMGuy23** [comment]
However, the Lua stuff means I can't compile
When that's fixed all will be great

**Comment by aflacc** [comment]
yeah magnus said he was thinking of adding modcharts himself which would really help

**Comment by VMGuy23** [comment]
Nice

**Comment by VMGuy23** [comment]
> yeah magnus said he was thinking of adding modcharts himself which would really help

It seemed he did. Compiling for all!
