### ISSUE TITLE
[10] Game enters death loop after entering any stage and dying for the first time.

### ISSUE THREAD

**Issue by Polytelus** [aflacc/ProjectFNF#55]
ProjectFNF version: V0.2-c
Type of issue: Mechanics
Severity: 10
Description:
Even after the newest commit to the master branch, such issues still may ocurr:
- Die in any stage.
- Enjoy unstoppable deaths trying to play anything else until you re-open the game.
Repository:
master

**Comment by aflacc** [comment]
![image](https://user-images.githubusercontent.com/60161366/120234044-f83b5980-c20b-11eb-8e12-5d064afad657.png)

**Comment by Polytelus** [comment]
Thanks!
I'm not a Discord member (and I don't intend to join servers that I know I
won't be active at), so I didn't knew this.

Em seg, 31 de mai de 2021 16:30, aflac ***@***.***> escreveu:

**Comment by MagnusStrom** [comment]
Update seems to be fixed, Looks like the health variable wasn't changing.
