### ISSUE TITLE
Game Version

### ISSUE THREAD

**Issue by UnknownSkid** [aflacc/ProjectFNF#58]
i dont wanna MAKE game
i wanna PLAY game

that means i dont want to use source code i just want a normal FNF with this engine

**Comment by VMGuy23** [comment]
Hi - There are build instructions in the Wiki. Follow them and then you can play the latest source version.
If you are having trouble, ask.
I might be able to build a Windows version for you later.

**Comment by UnknownSkid** [comment]
> Hi - There are build instructions in the Wiki. Follow them and then you can play the latest source version.
> If you are having trouble, ask.
> I might be able to build a Windows version for you later.

where is link how to build the game?

**Comment by VMGuy23** [comment]
Hi - There are build instructions in the [Setup section of the Wiki](https://github.com/aflacc/ProjectFNF/wiki/Setup-Workspace).

**Comment by aflacc** [comment]
If you want to just try out the engine you can either check out the [Itch.io](https://aflacck.itch.io/projectfnf) for occasional builds, or compile the game on your computer. Note that the itch.io isn't going to have all the latest stuff. I will put up a download maybe on there later

**Comment by UnknownSkid** [comment]
> Hi - There are build instructions in the Wiki. Follow them and then you can play the latest source version.
> If you are having trouble, ask.
> I might be able to build a Windows version for you later.

Please build the game

**Comment by VMGuy23** [comment]
Hi - I should have a Windows build ready for you in the next 24 hours. Sorry if it's a bit slow, I mainly work on Linux.

**Comment by VMGuy23** [comment]
Hi - Sorry for the delay, your build can be found [here](https://ufile.io/sp7r4s4f).
