### ISSUE TITLE
Windows Binaries

### ISSUE THREAD

**Issue by josechan50** [aflacc/ProjectFNF#6]
Can someone make windows (and maybe mac) binaries please? thanks

**Comment by aflacc** [comment]
What do you mean by a Binary

**Comment by josechan50** [comment]
> What do you mean by a Binary

.exe files (.dmg for Mac, .deb for debían)

**Comment by aflacc** [comment]
no idea what that label does

**Comment by aflacc** [comment]
but yeah do you want me to have a way to try the engine without actually getting the code?

**Comment by josechan50** [comment]
yes pleaseeeeeeeee

**Comment by josechan50** [comment]
also please release mac and windows demos/bins (question: whats your timezone?)

**Comment by aflacc** [comment]
> yes pleaseeeeeeeee

 I could remove the exports from the gitignore or I could put the full releases on the itch.io

> also please release mac and windows demos/bins (question: whats your timezone?)

Pacific Daylight time.

**Comment by AidenAnimates** [comment]
> I could remove the exports from the gitignore or I could put the full releases on the itch.io
You should put the releases on itch.io

**Comment by aflacc** [comment]
> > I could remove the exports from the gitignore or I could put the full releases on the itch.io
> > You should put the releases on itch.io

ye ok

**Comment by josechan50** [comment]
> > > I could remove the exports from the gitignore or I could put the full releases on the itch.io
> > > You should put the releases on itch.io
> 
> ye ok

d o   I t

**Comment by josechan50** [comment]
> > > I could remove the exports from the gitignore or I could put the full releases on the itch.io
> > > You should put the releases on itch.io
> 
> ye ok

please do it

**Comment by aflacc** [comment]
there is a demo on the itchio

**Comment by aflacc** [comment]
closing this now
