### ISSUE TITLE
Disable note miss animation

### ISSUE THREAD

**Issue by UserUNP** [aflacc/ProjectFNF#60]
Describe the type of Feature : Quality of Life
Describe your Suggestion: A setting in the options menu that sets a bool to true that lets you disable the miss animation when not hitting a note.

**Comment by aflacc** [comment]
IDK if we gonna get around to actually doing anything in the options menu

**Comment by aflacc** [comment]
If you want to disable this just go to lines `2080` and `2605` of `PlayState.hx` and delete the switch cases

**Comment by MagnusStrom** [comment]
This feature has now been added, but not in the binaries. Download the source code and compile to get this feature.

**Comment by UserUNP** [comment]
thanks manguns strom very cool i replied 5 days later cause i don't keep track of issues i write for some reason but thanks
