### ISSUE TITLE
[8] Freeze when selecting song (0.2-c)

### ISSUE THREAD

**Issue by thepercentageguy** [aflacc/ProjectFNF#61]
ProjectFNF version: 0.2-c
Type of issue: Crash/Freeze
Severity: 8
Description: Whenever i try to build & run the game (just freshly downloaded with no changes to the code) and i try to select a song the game freezes, and in debug mode it says it can't find the song IDs
Repository: None

![image](https://user-images.githubusercontent.com/54141759/121202206-67045c80-c875-11eb-91ab-883c46cdcdc0.png)

I don't know the source code all that well so i wouldn't know how to fix it myself

**Comment by aflacc** [comment]
Are you compiling in html5 because mp3s are the way html5 compiles. Try compiling with windows or mac or whatever OS you have.

**Comment by thepercentageguy** [comment]
> Are you compiling in html5 because mp3s are the way html5 compiles. Try compiling with windows or mac or whatever OS you have.

i'll try that thanks

**Comment by aflacc** [comment]
Not sure if thats the cause just I'm suggesting that you try compiling it as a executable instead of a browser.

**Comment by aflacc** [comment]
Browser compiles are really only good for debugging

**Comment by thepercentageguy** [comment]
compiling to executable worked, thanks

**Comment by aflacc** [comment]
Wait before you go, check the songs folder located from the root/assets/songs. look for the songs that were listed in the screenshot you sent check if theres .mp3's for them

**Comment by thepercentageguy** [comment]
> Wait before you go, check the songs folder located from the root/assets/songs. look for the songs that were listed in the screenshot you sent check if theres .mp3's for them

all of them have mp3's

**Comment by aflacc** [comment]
Check the export folder.
(root/export/) and find the html5 one
look in `assets/songs` and check if the mp3s are there

**Comment by thepercentageguy** [comment]
> Check the export folder.
> (root/export/) and find the html5 one
> look in `assets/songs` and check if the mp3s are there

They are, sorry for the late reply lol

**Comment by aflacc** [comment]
Does this issue still happen

**Comment by aflacc** [comment]
Hello? is this a thing still in html5?

**Comment by ZachToonz** [comment]
> Hello? is this a thing still in html5?
im guessing it is not but forgot to close it lol

**Comment by thepercentageguy** [comment]
Oop sorry haven't been online I'll check tomorrow

**Comment by aflacc** [comment]
did he check

**Comment by thepercentageguy** [comment]
shit
i'll check rn

**Comment by thepercentageguy** [comment]
it is

**Comment by MagnusStrom** [comment]
I'll be closing this because it's on an old version. try on the newest version

**Comment by thepercentageguy** [comment]
I did
