### ISSUE TITLE
[4] Boyfriend has no health (0.2-c)

### ISSUE THREAD

**Issue by Silvery2Actual** [aflacc/ProjectFNF#62]
ProjectFNF version: 0.2-c
Type of issue: Visual
Severity: 4
Description: When I load up a song to test, the health bar is stuck with giving Boyfriend no HP. I don't know why this happens, but it's now very hard to tell when you're about to die. (unsure if death is unavailable in this state)

**Comment by aflacc** [comment]
by any chance can you put the playstate file up somewhere like a pastebin so i can read it? this was an issue that I ended up fixing and I think I know the fix

**Comment by Silvery2Actual** [comment]
> by any chance can you put the playstate file up somewhere like a pastebin so i can read it? this was an issue that I ended up fixing and I think I know the fix

uhh i am unable to put it into pastebin

**Comment by aflacc** [comment]
idk i just need a way to read it

**Comment by MagnusStrom** [comment]
Hi, you're probably on an old version of ProjectFNF. Please download the newest version.
