### ISSUE TITLE
[2] Winter-Horrorland uses regular stage background

### ISSUE THREAD

**Issue by VMGuy23** [aflacc/ProjectFNF#65]
ProjectFNF version: Very latest from Git
Type of issue: visual
Severity: 2
Description: On Winter Horrorland it uses the default backup stage, as used in Tutorial and Week 1.
Repository: This one

**Comment by MagnusStrom** [comment]
Fixed, It seems. Download newest version of projectFNF.

**Comment by VMGuy23** [comment]
ok

**Comment by VMGuy23** [comment]
also can you add a little
```haxe
#if windows
```
to the modcharting so i can play on linux
