### ISSUE TITLE
dumb stupid issue why did i make this

### ISSUE THREAD

**Issue by nickpythonluajava** [aflacc/ProjectFNF#66]
why is there pog spirit on icongrid

**Comment by aflacc** [comment]
its best not to ask questions about things you cant physically comprehend

**Comment by MagnusStrom** [comment]
its winning icon dumbs

**Comment by aflacc** [comment]
magnus is correct

**Comment by nickpythonluajava** [comment]
> its winning icon dumbs

where is the other winning icons then
