### ISSUE TITLE
holy crap funny number

### ISSUE THREAD

**Issue by aflacc** [aflacc/ProjectFNF#69]
holy crap

**Comment by aflacc** [comment]
also nice number!!!!!!!!

**Comment by aflacc** [comment]
among us!

**Comment by aflacc** [comment]
if any admins see this in the discord ping everyone telling them we got funny number of issues >:D

**Comment by aflacc** [comment]
actually just do @here

**Comment by aflacc** [comment]
mag i will take your spine if you close this

**Comment by aflacc** [comment]
im getting my phone to do it myself

**Comment by nickpythonluajava** [comment]
FUNNY.
FRICKIN.
NUMBER.
HOLY CRAP.

**Comment by MagnusStrom** [comment]
L

**Comment by nickpythonluajava** [comment]
> L

you are going to fricking pay
