### ISSUE TITLE
[#] 70 probably

### ISSUE THREAD

**Issue by RobloxDonut** [aflacc/ProjectFNF#71]
ProjectFNF version 0.2-d
So the health bar is locked at the very end and you can't see what place you are actually at on the health bar which is pretty annoying. It could be a code issue, but I'm not too sure.
![Friday Night Funkin' ProjectFNF 6_17_21 11_17_43 AM](https://user-images.githubusercontent.com/63868549/122425855-c9d4b280-cf5d-11eb-9678-81cd4b1ea6d8.png)

**Comment by VMGuy23** [comment]
Where score bar?

**Comment by RobloxDonut** [comment]
> Where score bar?

what

**Comment by MagnusStrom** [comment]
Old version of projectFNF. please compile the latest version

**Comment by VMGuy23** [comment]
> > Where score bar?
> 
> what

score, rating, accuracy etc
