### ISSUE TITLE
[#] 71? something i have no fricking idea

### ISSUE THREAD

**Issue by RobloxDonut** [aflacc/ProjectFNF#72]
ProjectFNF version 0.2-d
Roses on freeplay kills you instantly
I selected freeplay and went to roses and i was greeted to an instant blue ball. I also retried and it didn't help.

**Comment by MagnusStrom** [comment]
I can't replicate this issue on Mac. Please download the newest version and let me know what happens.

> ProjectFNF version 0.2-d
> Roses on freeplay kills you instantly
> I selected freeplay and went to roses and i was greeted to an instant blue ball. I also retried and it didn't help.

**Comment by RobloxDonut** [comment]
> I can't replicate this issue on Mac. Please download the newest version and let me know what happens.
> 
> > ProjectFNF version 0.2-d
> > Roses on freeplay kills you instantly
> > I selected freeplay and went to roses and i was greeted to an instant blue ball. I also retried and it didn't help.

so the source code download link isn't updated and i can't test it yet.

**Comment by MagnusStrom** [comment]
A new update will be out in a few hours, please wait.

**Comment by MagnusStrom** [comment]
Please download the new update and try again. If this issue continues, open another ticket.
