### ISSUE TITLE
CURRENT BUG: Do not download newest version

### ISSUE THREAD

**Issue by MagnusStrom** [aflacc/ProjectFNF#73]
DO NOT DOWNLOAD NEWEST VERSION. I'm currently testing sum shit and I need it up there, excuse the unprofessionalism I just need this to work lol

**Comment by VMGuy23** [comment]
Please explain the issue
I experienced my first real dev feeling today: "it works and i don't know how or why"
Explain what broken

**Comment by george2781** [comment]
I'm going to do it anyway and nobody can stop me

**Comment by MagnusStrom** [comment]
> Please explain the issue
> I experienced my first real dev feeling today: "it works and i don't know how or why"
> Explain what broken

I was stealing shit from Kade Engine lol. just broke. Fixed now.
