### ISSUE TITLE
[💡] Remove ProjectFNF folder

### ISSUE THREAD

**Issue by nickpythonluajava** [aflacc/ProjectFNF#76]
Describe the type of Feature : Suggestion
Repository containing this feature : master
Describe your Suggestion:
Remove the ProjectFNF folder, when unzipping there are no files in it, I can't make a PR because idk how to delete it.

**Comment by george2781** [comment]
Could try it I guess, aflac may be planning to use that folder tho? IDK.

**Comment by VMGuy23** [comment]
Holdup
Will PR that

**Comment by nickpythonluajava** [comment]
> Holdup
> 
> Will PR that

did you pr it yet?

**Comment by VMGuy23** [comment]
i dont know how to use the web ui
