### ISSUE TITLE
[10] Bad license

### ISSUE THREAD

**Issue by HTV04** [aflacc/ProjectFNF#77]
The current license suffers from the exact same issues FNF's license currently does, due to its lack of terms. It should either be reverted to Apache or changed to something like the GPL v3.

EDIT: Set the severity to 10 because any mods using ProjectFNF's code are affected by this, and will continue to be if they don't use code under a new license

**Comment by aflacc** [comment]
when ninjamuffin fixes his i will fix mine

**Comment by HTV04** [comment]
> when ninjamuffin fixes his i will fix mine

Why?

**Comment by HTV04** [comment]
> when ninjamuffin fixes his i will fix mine

Why? The more commits you publish with the current license, the more mods will get affected by it.

**Comment by aflacc** [comment]
same would go with ninjamuffin

**Comment by HTV04** [comment]
> same would go with ninjamuffin

...and? What's stopping you from changing the license for ProjectFNF? Only FNF's latest commit is under the joke license, the code that ProjectFNF is based off of is still under the Apache license. In fact, you're technically violating it by changing the license.

**Comment by VMGuy23** [comment]
get a good license please

**Comment by aflacc** [comment]
I will when ninjamuffin does

**Comment by VMGuy23** [comment]
bruh just do it, your license means i can sue you for lots of money after getting 1 less than expected fps

**Comment by MagnusStrom** [comment]
Updated.
