### ISSUE TITLE
[10, Crash] It crashes the entire game when trying to play Week 5

### ISSUE THREAD

**Issue by Kxeo** [aflacc/ProjectFNF#81]
For some reason, it refuses to play Week 5. 

https://user-images.githubusercontent.com/50978401/124366268-1bdf2e80-dc14-11eb-903f-8c9703ff3f46.mp4

**Comment by Kxeo** [comment]
Sorry for the lag my computer sux :(

**Comment by VMGuy23** [comment]
Make sure new icons are disabled

**Comment by Kxeo** [comment]
There are no new icons to disable.

**Comment by MagnusStrom** [comment]
Please send me your settings.

**Comment by Kxeo** [comment]
The settings were in the video.

**Comment by MagnusStrom** [comment]
I can't replicate this issue, can anyone else?

**Comment by MagnusStrom** [comment]
If no one else can replicate this all I can say is mess with some settings or redownload.

**Comment by VMGuy23** [comment]
I can play Week 5 fine
