### ISSUE TITLE
[💡] sex mode

### ISSUE THREAD

**Issue by oofyboy** [aflacc/ProjectFNF#82]
Describe the type of Feature : sex mode
Repository containing this feature : sex mode
Describe your Suggestion: sex mode

 s e x m o d e

**Comment by VMGuy23** [comment]
wait until week 8

**Comment by VMGuy23** [comment]
![image](https://user-images.githubusercontent.com/81651922/124397585-a4d79200-dd08-11eb-858c-cdde576d2c52.png)
heres proof

**Comment by VMGuy23** [comment]
![image](https://user-images.githubusercontent.com/81651922/124397599-b5880800-dd08-11eb-9cf0-11592508241d.png)
see

**Comment by nickpythonluajava** [comment]
> ![image](https://user-images.githubusercontent.com/81651922/124397599-b5880800-dd08-11eb-9cf0-11592508241d.png)
> 
> see

time to uninstall funkin

**Comment by GamerTeos** [comment]
That's a fake ninjamuffin. The real one is @ninja_muffin99 not @ninjamuffin99_

**Comment by VMGuy23** [comment]
> That's a fake ninjamuffin. The real one is @ninja_muffin99 not @ninjamuffin99_. Also the real ninjamuffin changed his profile pic

oh whoops

**Comment by nickpythonluajava** [comment]
> That's a fake ninjamuffin. The real one is @ninja_muffin99 not @ninjamuffin99_. Also the real ninjamuffin changed his profile pic

thank GOD
