### ISSUE TITLE
BF's notes won't show up after the successful compilation of the game?

### ISSUE THREAD

**Issue by TheBanana78** [aflacc/ProjectFNF#83]
**ProjectFNF version:** 0.3-c
**Type of issue:** Visual
**Severity:** 6
**Description:** For some reason, when I compile my game everything looks fine but when I select a week, BF's notes won't show at all which makes it impossible to complete any week. 
![image](https://user-images.githubusercontent.com/82652849/124559555-17538980-de51-11eb-8f1d-3903a1d2ed54.png)

**Comment by VMGuy23** [comment]
Go into modifiers, check that Boyfreind notes visible is set to True

**Comment by TheBanana78** [comment]
> Go into modifiers, check that Boyfriend notes visible is set to True

Thank you, that fixed my issue.
