### ISSUE TITLE
[💡] implementing hscript-plus into the game. + one other feature.

### ISSUE THREAD

**Issue by ILuvGemz** [aflacc/ProjectFNF#85]
Describe the type of Feature : note velocity and hscript-plus implementation
Repository containing this feature : https://github.com/DleanJeans/hscript-plus

https://github.com/nebulazorua/andromeda-engine

Describe your Suggestion:

There is an upgraded version of hscript available that is capable of executing multiple variables or even full haxe scripts. I believe it could be an incredible upgrade to hscript since it can only declare 1 variable and cannot create functions. In my opinion, giving this a try will help make modcharts more convenient.

Additionally, a new feature to suggest would be from the andromeda engine’s note velocity feature. I don’t know if Nebula is okay with it, so I believe you should ask.

**Comment by MagnusStrom** [comment]
Oh this is what MU is using
Yeah sure, I can add

**Comment by MagnusStrom** [comment]
Closing, unneeded
