### ISSUE TITLE
An unexpected crash would happen if you press enter on the countdown? 

### ISSUE THREAD

**Issue by TheBanana78** [aflacc/ProjectFNF#86]
**ProjectFNF version:** 0.3-d(BETA)
**Type of issue:** Crash
**Severity:** 2
**Description:** When you pause the game and try to resume it, if you press enter on the countdown it will occur an unexpected crash for some reason.

Here's the video of the crash
https://user-images.githubusercontent.com/82652849/124902907-a353e580-dff8-11eb-9427-5a1522b0ff4a.mp4

**Comment by VMGuy23** [comment]
According to a discord message, "a feature"

**Comment by TheBanana78** [comment]
So it's a feature and not a bug?

**Comment by VMGuy23** [comment]
It's a "feature", as in, it's a bug that the devs are gonna leave in to prevent cheating

**Comment by MagnusStrom** [comment]
:trollface: i'll fix it later
