### ISSUE TITLE
[#] 3rd song not visible in story menu tracks

### ISSUE THREAD

**Issue by KiiKino** [aflacc/ProjectFNF#87]
ProjectFNF version: 0.3-c
Type of issue: Visual
Severity:  2
Description: Nothing really happens, more of a visual bug that's mission. This is the same for every week.
Repository:

]

**Comment by KiiKino** [comment]
Here's the story hx file: [](https://filebin.net/amb8t3m3actetilh)

**Comment by MagnusStrom** [comment]
Run `haxelib update`, then recompile.

**Comment by george2781** [comment]
Something to note: This exists in the precompiled versions of 0.3-c that are in the releases tab right now

**Comment by VMGuy23** [comment]
This also exists after haxelib update

**Comment by george2781** [comment]
So... this should be re-opened?

**Comment by VMGuy23** [comment]
Yes

**Comment by MagnusStrom** [comment]
I'm unable to replicate this.
please try `haxelib git openfl https://github.com/openfl/openfl` and try again

**Comment by KiiKino** [comment]
So i'm supposed to run that command, then recompile?

**Comment by VMGuy23** [comment]
yes, works

**Comment by KiiKino** [comment]
yup, recompiling with OpenFL fixed the issue, closing issue
