### ISSUE TITLE
[3] Greyscale arrows visual bug

### ISSUE THREAD

**Issue by george2781** [aflacc/ProjectFNF#90]
ProjectFNF version: 0.3-c
Type of issue: Visual
Severity: 3? (I'm a bit unsure)
Description:
The greyscale arrow theme doesn't work properly, to reproduce this issue just download a copy of v0.3-c and select the arrow theme, you should notice the bug the second the song loads.
![Screenshot (4)](https://user-images.githubusercontent.com/42376099/125109659-8d6b2100-e0db-11eb-924d-1c20be11b015.png)

**Comment by VMGuy23** [comment]
yeah the Greyscale skin is broken

**Comment by george2781** [comment]
Kinda ruined my attempt at FCing bopeebo on hard with all skins :/

**Comment by george2781** [comment]
I've actually noticed quite a few things broken with arrow theming at the moment, it resets every time you open the settings menu, some themes don't work in week 6 and then this issue

**Comment by MagnusStrom** [comment]
Greyscale was a suggestion from a user. It's removed in the latest update.
I'll look into those note issues.
