### ISSUE TITLE
[Latest Beta] [10] Tapping where there isn't a note results in crash

### ISSUE THREAD

**Issue by VMGuy23** [aflacc/ProjectFNF#91]
ProjectFNF version: 0.3-d (BETA) - Latest commit
Type of issue: Crash
Severity: 10
Description: On the latest commit, start a song in any way, then tap where there isn't a note. The game will crash.

**Comment by MagnusStrom** [comment]
Looking into this. I'm unable to replicate on debug mode.

**Comment by VMGuy23** [comment]
Latest commit, Linux, regular note skin, Release profile

**Comment by MagnusStrom** [comment]
Fixed, Had some unfinished shit. Pull and let me know.

**Comment by VMGuy23** [comment]
fixed
