### ISSUE TITLE
[#] Misses are too strict on the player / hitbox [9]

### ISSUE THREAD

**Issue by KiiKino** [aflacc/ProjectFNF#94]
ProjectFNF version: 0.3-c
Type of issue: Mechanic / Gameplay / Rating
Severity: 9
Description: Many of my hits are for some reason counted as misses (my accuracy is 70%, yet I have 170 misses). By the way, ghost tapping is off. The reason I have it disabled is because it ruins the point of a combo.
Repository: The accuracy / gameplay code was not touched.

**Comment by george2781** [comment]
Yeah, this is noticable in the precompiled 0.3-d versions as well

**Comment by MagnusStrom** [comment]
Can i get a video? I've seen some issues related to this update.

**Comment by MagnusStrom** [comment]
Is this issue still present in the beta?

**Comment by MagnusStrom** [comment]
FIXED
