### ISSUE TITLE
[8] Week 6 Arrows missing

### ISSUE THREAD

**Issue by Kxeo** [aflacc/ProjectFNF#99]
Project FNF 0.2-e-2
Severity is 8
The Week 6 Arrows are missing...
Recording: [I had to use Yandex.Disk to give the recording](https://disk.yandex.ru/d/-CUp8H72IxCidw)

**Comment by VMGuy23** [comment]
Hi - I am unable to replicate the issue. Please check that you are compiling with the latest commit (use `git fetch` then `git pull` to update), try recomliling and compiling with `-clean`. Please see attached screenshot.
![image](https://user-images.githubusercontent.com/81651922/126173644-cca76797-5e42-4fa8-b1b5-0911d8949860.png)

**Comment by VMGuy23** [comment]
Update: after checking all note skins with Thorns, none have acted like this. WAFELS3 crashed the game but none did this

**Comment by Kxeo** [comment]
Hmm... odd...

**Comment by VMGuy23** [comment]
What platform are you on? Also, it seems you are on an old version (0.2-e-2) when a much newer (0.3-d or 0.4-a-P) version is available. Download the latest

**Comment by Kxeo** [comment]
> Please check that you are compiling with the latest commit (use `git fetch` then `git pull` to update), try recompiling and compiling with `-clean`. Please see attached screenshot.
> ![image](https://user-images.githubusercontent.com/81651922/126173644-cca76797-5e42-4fa8-b1b5-0911d8949860.png)

Where do I even use those commands?

**Comment by VMGuy23** [comment]
Before you run those commands, download the latest ProjectFNF release from [here](../releases) (download the Windows zip) and see if you still have the problem.

**Comment by MagnusStrom** [comment]
that is a pretty outdated version of projectfnf

**Comment by Kxeo** [comment]
Apparently, itch.io was the problem.
It had a outdated ProjectFNF build. That's the problem.
I have downloaded the latest build, and the problem was fixed.
